language: go

sudo: false

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  
before_install:
  - chmod +x go.test.sh
  - go get -t -v ./...
  
script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

notifications:
  email: false