language: go

sudo: false

go:
  - "1.9"
  - "1.10"
  
before_install:
  - chmod +x go.test.sh
  - go get -t -v ./...
  
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

notifications:
  email: false